version: "3.7"
services:
    app:
        build:
            args:
                user: labsal
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: labsal
        container_name: labsal-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ./docker-compose/php/labsal.ini:/usr/local/etc/php/conf.d/labsal.ini
        networks:
            - labsal
    db:
        image: mysql:8
        container_name: labsal-db
        restart: unless-stopped
        ports:
            - 3300:3306
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql/init:/docker-entrypoint-initdb.d
            - ./docker-compose/mysql/persistent:/var/lib/mysql
        networks:
            - labsal
    nginx:
        image: nginx:1.19-alpine
        container_name: labsal-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - labsal
networks:
    labsal:
        driver: bridge